language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.clone("https://github.com/sisl/POMDPs.jl"); Pkg.clone("https://github.com/sisl/POMDPModels.jl"); Pkg.clone("https://github.com/sisl/POMDPToolbox.jl"); Pkg.clone("https://github.com/sisl/POMDPDisctributions.jl"); Pkg.test("DiscreteValueIteration")'
after_success:
  - julia -e 'cd(Pkg.dir("DiscreteValueIteration")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
